import { describe, expect, test } from 'bun:test';
import { allocateTransaction, canonicalTransaction, detectColumns, matchTransaction, normalizeName, parseBankAmount, parseBankDate, parseMappedRows, previewBatch, type BankPlayer, type BankPayment, type ReviewTransaction } from '../src/lib/bank-import';
const players:BankPlayer[]=[{id:'a',first_name:'საბა',last_name:'გიორგაძე',is_active:true,family_id:'family',created_at:'2026-01-01'},{id:'b',first_name:'ნიკა',last_name:'გიორგაძე',is_active:true,family_id:'family',created_at:'2026-01-02'},{id:'c',first_name:'ანა',last_name:'ბერიძე',is_active:true,created_at:'2026-01-03'}];
const payments:BankPayment[]=[{id:'a9',player_id:'a',year:2026,month:9,amount:170,paid_amount:70,status:'overdue'},{id:'b9',player_id:'b',year:2026,month:9,amount:170,paid_amount:0,status:'overdue'},{id:'a10',player_id:'a',year:2026,month:10,amount:170,paid_amount:0,status:'pending'}];
const tx={key:'tx',date:'2026-10-07',amount:300,sender:'Parent Giorgadze',purpose:'Training SABA, GIORGADZE payment'};
describe('bank reconciliation',()=>{
 test('transliterates Georgian, casing and punctuation',()=>{expect(normalizeName('ᲡᲐᲑᲐ გიორგაძე')).toBe('saba giorgadze');expect(matchTransaction(tx,players,[])).toEqual({playerId:'a',confidence:'high'});expect(matchTransaction({...tx,purpose:'Giorgadze fee for Saba'},players,[]).playerId).toBe('a');});
 test('aliases and unique surnames; ambiguity never guesses',()=>{expect(matchTransaction({...tx,purpose:'Private transfer'},players,[]).confidence).toBe('unmatched');expect(matchTransaction({...tx,purpose:'პირადი გადარიცხვა',sender:'მამა ბერიძე'},players,[])).toEqual({playerId:'c',confidence:'medium'});expect(matchTransaction({...tx,purpose:''},players,[{id:'alias',payer_name:'parent giorgadze',player_id:'b'}]).playerId).toBe('b');});
 test('family fills chronological month/member order without overflow',()=>{const p=allocateTransaction(300,'b',players,payments);expect(p.allocations.map(a=>[a.paymentId,a.amount,a.fullyPaid])).toEqual([['a9',100,true],['b9',170,true],['a10',30,false]]);expect(allocateTransaction(500,'a',players,payments).leftover).toBe(60);expect(allocateTransaction(20,'a',players,payments,'2026-10').allocations[0].paymentId).toBe('a10');});
 test('batch reserves balances and ignores duplicate preview overwrite',()=>{const row:ReviewTransaction={...tx,playerId:'a',confidence:'high',confirmed:true,remember:false,skip:false,duplicate:false,targetMonth:'',recorded:false,include:false,handled:false,futureDate:false};const batch=previewBatch([row,{...row,duplicate:true},{...row,key:'next',amount:150}],players,payments);expect(batch.get('tx')?.allocations.length).toBe(3);expect(batch.get('next')?.allocations[0].expectedPaid).toBe(30);expect(batch.get('next')?.leftover).toBe(10);});
 test('numbers, dates and transaction keys',()=>{expect(parseBankAmount('1.234,56')).toBe(1234.56);expect(parseBankAmount('(170.00)')).toBe(-170);expect(parseBankDate('07.10.2026')).toBe('2026-10-07');expect(parseBankDate('31.02.2026')).toBeNull();expect(canonicalTransaction(tx.date,300,tx.sender,tx.purpose,'ID')).toBe(canonicalTransaction('2025-01-01',20,'other','other','ID'));});
 test('header detection prioritises credit over general amount and ignores outgoing, fee/balance rows',()=>{const grid:unknown[][]=[['TBC account statement'],['თარიღი','Amount','Paid In','Paid Out',"Partner's Name",'Description','Transaction ID'],['07.10.2026',170,170,0,'Sender','Payment','1'],['07.10.2026',30,0,30,'Sender','Outgoing','2'],['07.10.2026',3,3,0,'TBC','საკომისიო','3'],['07.10.2026',500,500,0,'ნაშთი','','4']];const d=detectColumns(grid);expect(d.confident).toBe(true);expect(d.mapping.amount).toBe(2);const parsed=parseMappedRows(grid,d.headerRow,d.mapping);expect(parsed.transactions.length).toBe(1);expect(parsed.ignored).toBe(3);expect(detectColumns([['Date','Amount','Sender']]).confident).toBe(false);});
});
import { cleanPartnerName, detectDateOrder, isAlreadyRecorded, monthChanges, paysFutureMonth, rowIncluded } from '../src/lib/bank-import';
describe('TBC CSV fixes',()=>{
 test('day-first dates decided per column',()=>{expect(detectDateOrder(['01/09/2026','12/09/2026'])).toBe('dmy');expect(detectDateOrder(['09/13/2026','09/01/2026'])).toBe('mdy');expect(detectDateOrder(['13/09/2026','09/13/2026'])).toBe('dmy');expect(parseBankDate('01/09/2026')).toBe('2026-09-01');expect(parseBankDate('12/09/2026')).toBe('2026-09-12');expect(parseBankDate('09/13/2026','mdy')).toBe('2026-09-13');});
 test('TBC two-header CSV with signed amounts and partner ID',()=>{const grid:unknown[][]=[['თარიღი','აღწერა'],['Date','Description','Transaction Type','Amount','Currency','Account Number','Account Name','Additional Information','Document Date','Document Number',"Partner's Account","Partner's Name",'Transaction ID'],['01/09/2026','Incoming','Transfer','170.0','GEL','','','საბა გიორგაძე','','','',"ლელა ჭოხონელიძე, 01005027608",'T1'],['12/09/2026','Out','Transfer','-140.0','GEL','','','x','','','','Shop','T2']];const d=detectColumns(grid);expect(d.confident).toBe(true);const p=parseMappedRows(grid,d.headerRow,d.mapping);expect(p.transactions.length).toBe(1);expect(p.transactions[0].date).toBe('2026-09-01');expect(p.transactions[0].sender).toBe('ლელა ჭოხონელიძე');expect(p.transactions[0].purpose).toBe('Incoming საბა გიორგაძე');expect(cleanPartnerName('A B, 01005027608')).toBe('A B');});
 test('already recorded by nearby payment date or paid month',()=>{const pays:BankPayment[]=[{id:'s',player_id:'c',year:2026,month:9,amount:170,paid_amount:170,status:'paid',payment_date:'2026-09-03'}];expect(isAlreadyRecorded({date:'2026-09-01',amount:170},'c',players,pays)).toBe(true);expect(isAlreadyRecorded({date:'2026-09-20',amount:170},'c',players,pays)).toBe(true);expect(isAlreadyRecorded({date:'2026-10-20',amount:170},'c',players,pays)).toBe(false);});
 test('future month flag, exclusion and month summary',()=>{expect(paysFutureMonth('2026-09-15',[{year:2026,month:10}])).toBe(false);expect(paysFutureMonth('2026-09-15',[{year:2026,month:11}])).toBe(true);const pays:BankPayment[]=[{id:'n',player_id:'c',year:2026,month:11,amount:170,paid_amount:0,status:'pending'}];const row:ReviewTransaction={...tx,date:'2026-09-15',amount:170,playerId:'c',confidence:'high',confirmed:true,remember:false,skip:false,duplicate:false,targetMonth:'',recorded:false,include:false,handled:false,futureDate:false};const pv=previewBatch([row],players,pays);expect(pv.get('tx')?.futureMonth).toBe(true);expect(rowIncluded(row,pv.get('tx'))).toBe(false);const inc={...row,include:true};expect(monthChanges([inc],previewBatch([inc],players,pays))).toEqual([{month:'2026-11',count:1}]);expect(rowIncluded({...row,recorded:true},{allocations:[pv.get('tx')!.allocations[0]],leftover:0,futureMonth:false})).toBe(false);});
});
test('real TBC CSV: purpose from Description, not empty Additional Information',()=>{
 const geo=['თარიღი','აღწერა','ტრანზაქციის ტიპი','თანხა','ვალუტა','ანგარიშის ნომერი','ანგარიშის სახელი','დამატებითი ინფორმაცია','საბუთის თარიღი','საბუთის №','პარტნიორის ანგარიში','პარტნიორის დასახელება','პარტნიორის საგადასახადო კოდი','პარტნიორის ბანკის კოდი','პარტნიორის ბანკი','შუამავალი ბანკის კოდი','შუამავალი ბანკი','საკომისიოს დეტალები','გადასახადის გადამხდელის კოდი','გადასახადის გადამხდელის სახელი','ხაზინის კოდი','ოპ.კოდი','დამატებითი აღწერა','ტრანზაქციის id'];
 const eng=['Date','Description','Transaction Type','Amount','Currency','Account Number','Account Name','Additional Information','Document Date','Document Number',"Partner's Account","Partner's Name","Partner's Tax Code","Partner's Bank Code","Partner's Bank",'Intermediary Bank Code','Intermediary Bank','Charge Details','Taxpayer Code','Taxpayer Name','Treasury Code','Op.Code','Additional Description','Transaction ID'];
 const row=['02/09/2026','გაბრიელ შალამბერიძე','შემოსავალი','170.0','GEL','GE56TB7945736080100010','შპს მართვე','','02/09/2026','1788367908','GE33TB7988945068100028','ლელა ჭოხონელიძე, 01005027608','01005027608','TBCBGE22','სს "თიბისი ბანკი"','','','','01005027608','ლელა ჭოხონელიძე, 01005027608','','GMB','','21072229271.20'];
 const d=detectColumns([geo,eng,row]);
 expect(d.confident).toBe(true);
 expect(d.headerRow).toBe(0);
 const p=parseMappedRows([geo,eng,row],d.headerRow,d.mapping);
 expect(p.transactions.length).toBe(1);
 expect(p.transactions[0].date).toBe('2026-09-02');
 expect(p.transactions[0].amount).toBe(170);
 expect(p.transactions[0].purpose).toBe('გაბრიელ შალამბერიძე');
 expect(p.transactions[0].sender).toBe('ლელა ჭოხონელიძე');
 expect(p.transactions[0].identity).toBe('tbc:id:21072229271.20');
 // empty Description falls back to Additional Information for that row
 const row2=[...row];row2[1]='';row2[7]='საბა გიორგაძე';row2[23]='T-other';
 const p2=parseMappedRows([eng,row2],0,detectColumns([eng,row2]).mapping);
 expect(p2.transactions[0].purpose).toBe('საბა გიორგაძე');
});
