import { describe, expect, test } from 'bun:test';
import { allocateTransaction, canonicalTransaction, detectColumns, matchTransaction, normalizeName, parseBankAmount, parseBankDate, parseMappedRows, previewBatch, type BankPlayer, type BankPayment, type ReviewTransaction } from '../src/lib/bank-import';
const players:BankPlayer[]=[{id:'a',first_name:'საბა',last_name:'გიორგაძე',is_active:true,family_id:'family',created_at:'2026-01-01'},{id:'b',first_name:'ნიკა',last_name:'გიორგაძე',is_active:true,family_id:'family',created_at:'2026-01-02'},{id:'c',first_name:'ანა',last_name:'ბერიძე',is_active:true,created_at:'2026-01-03'}];
const payments:BankPayment[]=[{id:'a9',player_id:'a',year:2026,month:9,amount:170,paid_amount:70,status:'overdue'},{id:'b9',player_id:'b',year:2026,month:9,amount:170,paid_amount:0,status:'overdue'},{id:'a10',player_id:'a',year:2026,month:10,amount:170,paid_amount:0,status:'pending'}];
const tx={key:'tx',date:'2026-10-07',amount:300,sender:'Parent Giorgadze',purpose:'Training SABA, GIORGADZE payment'};
describe('bank reconciliation',()=>{
 test('transliterates Georgian, casing and punctuation',()=>{expect(normalizeName('ᲡᲐᲑᲐ გიორგაძე')).toBe('saba giorgadze');expect(matchTransaction(tx,players,[])).toEqual({playerId:'a',confidence:'high'});expect(matchTransaction({...tx,purpose:'Giorgadze fee for Saba'},players,[]).playerId).toBe('a');});
 test('aliases and unique surnames; ambiguity never guesses',()=>{expect(matchTransaction({...tx,purpose:'Private transfer'},players,[]).confidence).toBe('unmatched');expect(matchTransaction({...tx,purpose:'პირადი გადარიცხვა',sender:'მამა ბერიძე'},players,[])).toEqual({playerId:'c',confidence:'medium'});expect(matchTransaction({...tx,purpose:''},players,[{id:'alias',payer_name:'parent giorgadze',player_id:'b'}]).playerId).toBe('b');});
 test('family fills chronological month/member order without overflow',()=>{const p=allocateTransaction(300,'b',players,payments);expect(p.allocations.map(a=>[a.paymentId,a.amount,a.fullyPaid])).toEqual([['a9',100,true],['b9',170,true],['a10',30,false]]);expect(allocateTransaction(500,'a',players,payments).leftover).toBe(60);expect(allocateTransaction(20,'a',players,payments,'2026-10').allocations[0].paymentId).toBe('a10');});
 test('batch reserves balances and ignores duplicate preview overwrite',()=>{const row:ReviewTransaction={...tx,playerId:'a',confidence:'high',confirmed:true,remember:false,skip:false,duplicate:false,targetMonth:''};const batch=previewBatch([row,{...row,duplicate:true},{...row,key:'next',amount:150}],players,payments);expect(batch.get('tx')?.allocations.length).toBe(3);expect(batch.get('next')?.allocations[0].expectedPaid).toBe(30);expect(batch.get('next')?.leftover).toBe(10);});
 test('numbers, dates and transaction keys',()=>{expect(parseBankAmount('1.234,56')).toBe(1234.56);expect(parseBankAmount('(170.00)')).toBe(-170);expect(parseBankDate('07.10.2026')).toBe('2026-10-07');expect(parseBankDate('31.02.2026')).toBeNull();expect(canonicalTransaction(tx.date,300,tx.sender,tx.purpose,'ID')).toBe(canonicalTransaction('2025-01-01',20,'other','other','ID'));});
 test('header detection prioritises credit over general amount and ignores outgoing, fee/balance rows',()=>{const grid:unknown[][]=[['TBC account statement'],['თარიღი','Amount','Paid In','Paid Out',"Partner's Name",'Description','Transaction ID'],['07.10.2026',170,170,0,'Sender','Payment','1'],['07.10.2026',30,0,30,'Sender','Outgoing','2'],['07.10.2026',3,3,0,'TBC','საკომისიო','3'],['07.10.2026',500,500,0,'ნაშთი','','4']];const d=detectColumns(grid);expect(d.confident).toBe(true);expect(d.mapping.amount).toBe(2);const parsed=parseMappedRows(grid,d.headerRow,d.mapping);expect(parsed.transactions.length).toBe(1);expect(parsed.ignored).toBe(3);expect(detectColumns([['Date','Amount','Sender']]).confident).toBe(false);});
});
