/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksSendPaymentSmsRouteImport } from './routes/hooks/send-payment-sms'
import { Route as ApiCoachScheduleRouteImport } from './routes/api/coach/schedule'
import { Route as ApiCoachResetPasswordRouteImport } from './routes/api/coach/reset-password'
import { Route as ApiCoachRegisterRouteImport } from './routes/api/coach/register'
import { Route as ApiCoachLoginRouteImport } from './routes/api/coach/login'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksSendPaymentSmsRoute = HooksSendPaymentSmsRouteImport.update({
  id: '/hooks/send-payment-sms',
  path: '/hooks/send-payment-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachScheduleRoute = ApiCoachScheduleRouteImport.update({
  id: '/api/coach/schedule',
  path: '/api/coach/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachResetPasswordRoute = ApiCoachResetPasswordRouteImport.update({
  id: '/api/coach/reset-password',
  path: '/api/coach/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRegisterRoute = ApiCoachRegisterRouteImport.update({
  id: '/api/coach/register',
  path: '/api/coach/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachLoginRoute = ApiCoachLoginRouteImport.update({
  id: '/api/coach/login',
  path: '/api/coach/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/hooks/send-payment-sms': typeof HooksSendPaymentSmsRoute
  '/api/coach/login': typeof ApiCoachLoginRoute
  '/api/coach/register': typeof ApiCoachRegisterRoute
  '/api/coach/reset-password': typeof ApiCoachResetPasswordRoute
  '/api/coach/schedule': typeof ApiCoachScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/hooks/send-payment-sms': typeof HooksSendPaymentSmsRoute
  '/api/coach/login': typeof ApiCoachLoginRoute
  '/api/coach/register': typeof ApiCoachRegisterRoute
  '/api/coach/reset-password': typeof ApiCoachResetPasswordRoute
  '/api/coach/schedule': typeof ApiCoachScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/hooks/send-payment-sms': typeof HooksSendPaymentSmsRoute
  '/api/coach/login': typeof ApiCoachLoginRoute
  '/api/coach/register': typeof ApiCoachRegisterRoute
  '/api/coach/reset-password': typeof ApiCoachResetPasswordRoute
  '/api/coach/schedule': typeof ApiCoachScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/hooks/send-payment-sms'
    | '/api/coach/login'
    | '/api/coach/register'
    | '/api/coach/reset-password'
    | '/api/coach/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/hooks/send-payment-sms'
    | '/api/coach/login'
    | '/api/coach/register'
    | '/api/coach/reset-password'
    | '/api/coach/schedule'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/hooks/send-payment-sms'
    | '/api/coach/login'
    | '/api/coach/register'
    | '/api/coach/reset-password'
    | '/api/coach/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  HooksSendPaymentSmsRoute: typeof HooksSendPaymentSmsRoute
  ApiCoachLoginRoute: typeof ApiCoachLoginRoute
  ApiCoachRegisterRoute: typeof ApiCoachRegisterRoute
  ApiCoachResetPasswordRoute: typeof ApiCoachResetPasswordRoute
  ApiCoachScheduleRoute: typeof ApiCoachScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/send-payment-sms': {
      id: '/hooks/send-payment-sms'
      path: '/hooks/send-payment-sms'
      fullPath: '/hooks/send-payment-sms'
      preLoaderRoute: typeof HooksSendPaymentSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach/schedule': {
      id: '/api/coach/schedule'
      path: '/api/coach/schedule'
      fullPath: '/api/coach/schedule'
      preLoaderRoute: typeof ApiCoachScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach/reset-password': {
      id: '/api/coach/reset-password'
      path: '/api/coach/reset-password'
      fullPath: '/api/coach/reset-password'
      preLoaderRoute: typeof ApiCoachResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach/register': {
      id: '/api/coach/register'
      path: '/api/coach/register'
      fullPath: '/api/coach/register'
      preLoaderRoute: typeof ApiCoachRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach/login': {
      id: '/api/coach/login'
      path: '/api/coach/login'
      fullPath: '/api/coach/login'
      preLoaderRoute: typeof ApiCoachLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  HooksSendPaymentSmsRoute: HooksSendPaymentSmsRoute,
  ApiCoachLoginRoute: ApiCoachLoginRoute,
  ApiCoachRegisterRoute: ApiCoachRegisterRoute,
  ApiCoachResetPasswordRoute: ApiCoachResetPasswordRoute,
  ApiCoachScheduleRoute: ApiCoachScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
